### ISSUE TITLE
v0.11 application crashes in dispatch.hpp

### ISSUE THREAD

**Issue by bioothod** [cocaine/cocaine-core#129]
Hi

Elliptics srw test application (https://github.com/reverbrain/elliptics/blob/master/tests/srw_test_app.cpp) regiulary crashes when building in vagrant. Here is a backtrace:

```
#0  malloc_consolidate (av=av@entry=0x2b40bd857760 <main_arena>) at malloc.c:4165
#1  0x00002b40bd517fed in _int_free (av=0x2b40bd857760 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4057
#2  0x00002b40bc07ef90 in deallocate (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8/ext/new_allocator.h:110
#3  _M_deallocate (this=<optimized out>, __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:174
#4  ~_Vector_base (this=0x1c92118, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:160
#5  ~vector (this=0x1c92118, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:416
#6  ~writable_stream (this=0x1c920c8, __in_chrg=<optimized out>) at /usr/include/cocaine/asio/writable_stream.hpp:31
#7  destroy<cocaine::io::writable_stream<cocaine::io::socket<cocaine::io::local> > > (this=<optimized out>, __p=0x1c920c8)
    at /usr/include/c++/4.8/ext/new_allocator.h:124
#8  _S_destroy<cocaine::io::writable_stream<cocaine::io::socket<cocaine::io::local> > > (__a=..., __p=0x1c920c8)
    at /usr/include/c++/4.8/bits/alloc_traits.h:281
#9  destroy<cocaine::io::writable_stream<cocaine::io::socket<cocaine::io::local> > > (__a=..., __p=0x1c920c8)
    at /usr/include/c++/4.8/bits/alloc_traits.h:405
#10 std::_Sp_counted_ptr_inplace<cocaine::io::writable_stream<cocaine::io::socket<cocaine::io::local> >, std::allocator<cocaine::io::writable_stream<cocaine::io::socket<cocaine::io::local> > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=<optimized out>)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:407
#11 0x00002b40bc056579 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x1c920b0)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:144
#12 0x00002b40bc07f086 in ~__shared_count (this=0x1c7f110, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:546
#13 ~__shared_ptr (this=0x1c7f108, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/shared_ptr_base.h:781
#14 ~shared_ptr (this=0x1c7f108, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/shared_ptr.h:93
#15 ~encoder (this=0x1c7f0c0, __in_chrg=<optimized out>) at /usr/include/cocaine/rpc/encoder.hpp:42
---Type <return> to continue, or q <return> to quit---
#16 operator() (this=<optimized out>, __ptr=0x1c7f0c0) at /usr/include/c++/4.8/bits/unique_ptr.h:67
#17 ~unique_ptr (this=0x1c7f4d8, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/unique_ptr.h:184
#18 ~channel (this=0x1c7f4d0, __in_chrg=<optimized out>) at /usr/include/cocaine/rpc/channel.hpp:33
#19 std::_Sp_counted_ptr<cocaine::io::channel<cocaine::io::socket<cocaine::io::local> >*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (
    this=<optimized out>) at /usr/include/c++/4.8/bits/shared_ptr_base.h:290
#20 0x0000000000416199 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x1c7f2e0)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:144
#21 0x000000000041087c in ~__shared_count (this=0x1c7f690, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8/bits/shared_ptr_base.h:546
#22 ~__shared_ptr (this=0x1c7f688, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/shared_ptr_base.h:781
#23 ~shared_ptr (this=0x1c7f688, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/shared_ptr.h:93
#24 ~dispatch_t (this=0x1c7f580, __in_chrg=<optimized out>) at /usr/include/cocaine/framework/dispatch.hpp:48
#25 std::default_delete<cocaine::framework::dispatch_t>::operator() (__ptr=__ptr@entry=0x1c7f580, this=<optimized out>)
    at /usr/include/c++/4.8/bits/unique_ptr.h:67
#26 0x000000000041b88a in ~unique_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8/bits/unique_ptr.h:184
#27 cocaine::framework::run<app_context<> > (argc=<optimized out>, argv=<optimized out>)
    at /usr/include/cocaine/framework/dispatch.hpp:236
#28 0x00002b40bd4b9ec5 in __libc_start_main (main=0x40f890 <main(int, char**)>, argc=9, argv=0x7fff972e44c8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff972e44b8) at libc-start.c:287
#29 0x000000000040fb60 in _start ()
```

cocaine-core and native framework are the latest checkouts from v0.11 branches
Does this fire the light or you need more help?

Server logs contain among other cocaine lines the following 'committed suicide' note:
```
2014-09-17 01:29:34.304526 0000000000000000/4399/4332 DEBUG: slave 41415dd3-61ea-49e5-a707-cc861be17517 received type 2 message in session 0, attrs: ['source': 'srw', 'app': 'app/dnet_cpp_srw_test_app']
2014-09-17 01:29:34.304549 0000000000000000/4378/4332 DEBUG: processing type 0 message using slot 'emit', attrs: ['source': 'srw', 'app': 'service/logging']
2014-09-17 01:29:34.304753 0000000000000000/4399/4332 DEBUG: slave 41415dd3-61ea-49e5-a707-cc861be17517 is committing suicide: per request, attrs: ['source': 'srw', 'app': 'app/dnet_cpp_srw_test_app']
2014-09-17 01:29:34.304865 0000000000000000/4378/4332 DEBUG: worker 41415dd3-61ea-49e5-a707-cc861be17517 received type 2 message, attrs: ['source': 'srw', 'app': 'app/dnet_cpp_srw_test_app']
2014-09-17 01:29:34.304982 0000000000000000/4399/4332 DEBUG: slave 36390bc3-a85a-4b82-951c-02dac78cd9fe received type 2 message in session 0, attrs: ['source': 'srw', 'app': 'app/dnet_cpp_srw_test_app']
2014-09-17 01:29:34.305310 0000000000000000/4378/4332 DEBUG: processing type 0 message using slot 'emit', attrs: ['source': 'srw', 'app': 'service/logging']
2014-09-17 01:29:34.305428 0000000000000000/4399/4332 DEBUG: slave 36390bc3-a85a-4b82-951c-02dac78cd9fe is committing suicide: per request, attrs: ['source': 'srw', 'app': 'app/dnet_cpp_srw_test_app']
2014-09-17 01:29:34.305498 0000000000000000/4378/4332 DEBUG: worker 36390bc3-a85a-4b82-951c-02dac78cd9fe received type 2 message, attrs: ['source': 'srw', 'app': 'app/dnet_cpp_srw_test_app']
2014-09-17 01:29:34.305814 0000000000000000/4399/4332 DEBUG: slave 41415dd3-61ea-49e5-a707-cc861be17517 has been terminated, attrs: ['source': 'srw', 'app': 'app/dnet_cpp_srw_test_app']
```

**Comment by Kobolog** [comment]
I'm not sure about what's going on here, so I'll just close it.
